### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by SlavianUA** [SlavianUA/DotLiblares#1]
# TODO List

## VideoEngine

- [x] Creating andvanced window
- [x] Creating Sprites
- [ ] Creating camera
- [ ] Creating maps

## Physic Engine

- [x] Implement Input
- [ ] Implements Physic

## Sound Engine

- [ ]  Creating music
- [ ]  Creating sound

## GUI Engine

- [ ]  Creating Buttons
- [ ]  Creating text edit fields
- [ ]  Creating simple text
